sudo: required
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=2.3.2
    - env: ANSIBLE_VERSION=2.4.2

before_install:
  - sudo apt-get -y install software-properties-common
  - sudo apt-get -y install python-pip
  - sudo pip install ansible==$ANSIBLE_VERSION
  - sudo pip install -U urllib3[secure]
  - ansible --version

install:
  - sudo mkdir /etc/fake_api/
  - sudo cp ./tests/files/fake_api.py /etc/fake_api/fake_api.py
  - sudo cp ./tests/files/fake_api.conf /etc/init/fake_api.conf

before_script:
  - sudo service fake_api start

script:
  - cd ./tests/
  - make

after_script:
  - sudo service fake_api stop
  - sudo cat /var/log/upstart/fake_api.log
