dist: focal

language: python
python: "3.9"

install:
  - pip3 install -r requirements.txt
  - ansible --version

script:
  - cd ./tests/
  - python3 ./files/fake_api.py & 2>&1 > ../tests/fake_api.log
  - make

after_script:
  - cat ./tests/fake_api.log
