dist: focal

language: python
python: "3.9"

#matrix:
#  include:
#    - env: ANSIBLE_VERSION=6.0.0

install:
  - pip3 install -r requirements.txt
  - ansible --version

#install:
 # - sudo mkdir /etc/fake_api/
 # - sudo cp ./tests/files/fake_api.py /etc/fake_api/fake_api.py
 # - sudo cp ./tests/files/fake_api.service /etc/systemd/system/

#before_script:
 #- sudo systemctl start fake_api

script:
  - python3 ./tests/files/fake_api.py &
  - cd ./tests/
  - make

#after_script:
 # - sudo systemctl stop fake_api
  #- sudo cat /var/log/upstart/fake_api.log
