name: Tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ansible tests
      run: |
        cd ./tests/
        python3 ./files/fake_api.py &
        make
